### ISSUE TITLE
tests fail with minitest

### ISSUE THREAD

**Issue by ktdreyer** [thoughtbot/shoulda-context#33]
I'm packaging shoulda-context for Fedora. When I run the test suite, and the minitest gem is installed, the test suite fails. Here's the command invocation I'm using:

```
testrb -Ilib:test test/shoulda/*_test.rb
```

The tests pass on Fedora 19 because minitest does not get pulled into the build root, and shoulda-context can just use test-unit. On Fedora 20 and 21, the minitest gem is installed (probably because some other gem requires it), and when it is present, the test suite fails.

```
+ testrb -Ilib:test test/shoulda/autoload_macro_test.rb test/shoulda/context_test.rb test/shoulda/convert_to_should_syntax_test.rb test/shoulda/helpers_test.rb test/shoulda/should_test.rb
*** Mocha deprecation warning: Change `require 'mocha'` to `require 'mocha/setup'`.
  * DEFERRED: Context should pass, since it's unimplemented. 
  * DEFERRED: Context should not require a block when using should_eventually. 
  * DEFERRED: Context should pass without a block, as that causes it to piggyback to should_eventually. 
  * DEFERRED: context for testing should piggybacking should call should_eventually as we are not passing a block. 
  * DEFERRED: context with nested subcontexts should only print this statement once for a should_eventually. 
  * DEFERRED: Context should be able to setup a should eventually in a class method. 
  * DEFERRED: Should should pass, since it's a should_eventually. 
Run options: -Ilib:test
# Running tests:
.....F.F....F.F.F.........E..EEE..EE.E..EEEEEEE.EEEEEEEEEEEEEEEE...F.F......FF...F.........................
Finished tests in 0.159908s, 669.1340 tests/s, 800.4594 assertions/s.
  1) Failure:
ContextTest#test: another context with setup block should have name set right.  [/builddir/build/BUILD/shoulda-context-1.1.5/usr/share/gems/gems/shoulda-context-1.1.5/test/shoulda/context_test.rb:66]:
Expected /^test: another context with setup block/ to match "#<ContextTest:0x9f1477c>".
  2) Failure:
ContextTest#test: context with method definition should have name set right.  [/builddir/build/BUILD/shoulda-context-1.1.5/usr/share/gems/gems/shoulda-context-1.1.5/test/shoulda/context_test.rb:80]:
Expected /^test: context with method definition/ to match "#<ContextTest:0x9f1864c>".
  3) Failure:
ContextTest#test: context with setup block and a subcontext should be named correctly.  [/builddir/build/BUILD/shoulda-context-1.1.5/usr/share/gems/gems/shoulda-context-1.1.5/test/shoulda/context_test.rb:32]:
Expected /^test: context with setup block and a subcontext should be named correctly/ to match "#<ContextTest:0x9f207c0>".
  4) Failure:
ContextTest#test: context with setup block should have name set right.  [/builddir/build/BUILD/shoulda-context-1.1.5/usr/share/gems/gems/shoulda-context-1.1.5/test/shoulda/context_test.rb:23]:
Expected /^test: context with setup block/ to match "#<ContextTest:0x9f25464>".
  5) Failure:
ContextTest#test: context with setup block with a subcontext made by a macro should have name set right.  [/builddir/build/BUILD/shoulda-context-1.1.5/usr/share/gems/gems/shoulda-context-1.1.5/test/shoulda/context_test.rb:42]:
Expected /^test: context with setup block with a subcontext made by a macro should have name set right/ to match "#<ContextTest:0x9f2af18>".
  6) Failure:
ShouldTest#test: Context with setup block and a subcontext should be named correctly.  [/builddir/build/BUILD/shoulda-context-1.1.5/usr/share/gems/gems/shoulda-context-1.1.5/test/shoulda/should_test.rb:93]:
Expected /^test: Context with setup block and a subcontext should be named correctly/ to match "#<ShouldTest:0xa251bd8>".
  7) Failure:
ShouldTest#test: Context with a subcontext a macro should have the tests named correctly.  [/builddir/build/BUILD/shoulda-context-1.1.5/usr/share/gems/gems/shoulda-context-1.1.5/test/shoulda/should_test.rb:43]:
Expected /^test: Context with a subcontext a macro should have the tests named correctly/ to match "#<ShouldTest:0xa252e34>".
  8) Failure:
ShouldTest#test: Context a macro should have the tests named correctly.  [/builddir/build/BUILD/shoulda-context-1.1.5/usr/share/gems/gems/shoulda-context-1.1.5/test/shoulda/should_test.rb:43]:
Expected /^test: Context a macro should have the tests named correctly/ to match "#<ShouldTest:0xa23ec18>".
  9) Failure:
ShouldTest#test: Another context with setup block should have name set right.  [/builddir/build/BUILD/shoulda-context-1.1.5/usr/share/gems/gems/shoulda-context-1.1.5/test/shoulda/should_test.rb:113]:
Expected /^test: Another context with setup block/ to match "#<ShouldTest:0xa22e548>".
 10) Failure:
ShouldTest#test: Context with setup block should have name set right.  [/builddir/build/BUILD/shoulda-context-1.1.5/usr/share/gems/gems/shoulda-context-1.1.5/test/shoulda/should_test.rb:84]:
Expected /^test: Context with setup block/ to match "#<ShouldTest:0xa2598b0>".
 11) Error:
HelpersTest#test: a matching matcher when given to assert_rejects and matcher does not have :does_not_match? should use the error message from the matcher. :
NameError: uninitialized constant Test::Unit::AssertionFailedError
    /builddir/build/BUILD/shoulda-context-1.1.5/usr/share/gems/gems/shoulda-context-1.1.5/test/shoulda/helpers_test.rb:85:in `rescue in block (4 levels) in <class:HelpersTest>'
    /builddir/build/BUILD/shoulda-context-1.1.5/usr/share/gems/gems/shoulda-context-1.1.5/test/shoulda/helpers_test.rb:83:in `block (4 levels) in <class:HelpersTest>'
    /builddir/build/BUILD/shoulda-context-1.1.5/usr/share/gems/gems/shoulda-context-1.1.5/lib/shoulda/context/context.rb:418:in `call'
    /builddir/build/BUILD/shoulda-context-1.1.5/usr/share/gems/gems/shoulda-context-1.1.5/lib/shoulda/context/context.rb:418:in `block in run_current_setup_blocks'
    /builddir/build/BUILD/shoulda-context-1.1.5/usr/share/gems/gems/shoulda-context-1.1.5/lib/shoulda/context/context.rb:417:in `each'
    /builddir/build/BUILD/shoulda-context-1.1.5/usr/share/gems/gems/shoulda-context-1.1.5/lib/shoulda/context/context.rb:417:in `run_current_setup_blocks'
    /builddir/build/BUILD/shoulda-context-1.1.5/usr/share/gems/gems/shoulda-context-1.1.5/lib/shoulda/context/context.rb:399:in `block in create_test_from_should_hash'
 12) Error:
HelpersTest#test: a non-matching matcher should fail when given to assert_rejects with a non-matching message. :
NameError: uninitialized constant Test::Unit::AssertionFailedError
    /builddir/build/BUILD/shoulda-context-1.1.5/usr/share/gems/gems/shoulda-context-1.1.5/test/shoulda/helpers_test.rb:116:in `block (2 levels) in <class:HelpersTest>'
    /builddir/build/BUILD/shoulda-context-1.1.5/usr/share/gems/gems/shoulda-context-1.1.5/lib/shoulda/context/context.rb:400:in `call'
    /builddir/build/BUILD/shoulda-context-1.1.5/usr/share/gems/gems/shoulda-context-1.1.5/lib/shoulda/context/context.rb:400:in `block in create_test_from_should_hash'
 13) Error:
HelpersTest#test: a non-matching matcher when given to assert_accepts should fail. :
NameError: uninitialized constant Test::Unit::AssertionFailedError
    /builddir/build/BUILD/shoulda-context-1.1.5/usr/share/gems/gems/shoulda-context-1.1.5/test/shoulda/helpers_test.rb:125:in `rescue in block (3 levels) in <class:HelpersTest>'
    /builddir/build/BUILD/shoulda-context-1.1.5/usr/share/gems/gems/shoulda-context-1.1.5/test/shoulda/helpers_test.rb:123:in `block (3 levels) in <class:HelpersTest>'
    /builddir/build/BUILD/shoulda-context-1.1.5/usr/share/gems/gems/shoulda-context-1.1.5/lib/shoulda/context/context.rb:418:in `call'
    /builddir/build/BUILD/shoulda-context-1.1.5/usr/share/gems/gems/shoulda-context-1.1.5/lib/shoulda/context/context.rb:418:in `block in run_current_setup_blocks'
    /builddir/build/BUILD/shoulda-context-1.1.5/usr/share/gems/gems/shoulda-context-1.1.5/lib/shoulda/context/context.rb:417:in `each'
    /builddir/build/BUILD/shoulda-context-1.1.5/usr/share/gems/gems/shoulda-context-1.1.5/lib/shoulda/context/context.rb:417:in `run_current_setup_blocks'
    /builddir/build/BUILD/shoulda-context-1.1.5/usr/share/gems/gems/shoulda-context-1.1.5/lib/shoulda/context/context.rb:399:in `block in create_test_from_should_hash'
 14) Error:
HelpersTest#test: a non-matching matcher when given to assert_accepts should use the error message from the matcher. :
NameError: uninitialized constant Test::Unit::AssertionFailedError
    /builddir/build/BUILD/shoulda-context-1.1.5/usr/share/gems/gems/shoulda-context-1.1.5/test/shoulda/helpers_test.rb:125:in `rescue in block (3 levels) in <class:HelpersTest>'
    /builddir/build/BUILD/shoulda-context-1.1.5/usr/share/gems/gems/shoulda-context-1.1.5/test/shoulda/helpers_test.rb:123:in `block (3 levels) in <class:HelpersTest>'
    /builddir/build/BUILD/shoulda-context-1.1.5/usr/share/gems/gems/shoulda-context-1.1.5/lib/shoulda/context/context.rb:418:in `call'
    /builddir/build/BUILD/shoulda-context-1.1.5/usr/share/gems/gems/shoulda-context-1.1.5/lib/shoulda/context/context.rb:418:in `block in run_current_setup_blocks'
    /builddir/build/BUILD/shoulda-context-1.1.5/usr/share/gems/gems/shoulda-context-1.1.5/lib/shoulda/context/context.rb:417:in `each'
    /builddir/build/BUILD/shoulda-context-1.1.5/usr/share/gems/gems/shoulda-context-1.1.5/lib/shoulda/context/context.rb:417:in `run_current_setup_blocks'
    /builddir/build/BUILD/shoulda-context-1.1.5/usr/share/gems/gems/shoulda-context-1.1.5/lib/shoulda/context/context.rb:399:in `block in create_test_from_should_hash'
 15) Error:
HelpersTest#test: an array of values should be the same as another array, ordered differently. :
NameError: uninitialized constant Test::Unit::AssertionFailedError
    /builddir/build/BUILD/shoulda-context-1.1.5/usr/share/gems/gems/shoulda-context-1.1.5/test/shoulda/helpers_test.rb:26:in `block (2 levels) in <class:HelpersTest>'
    /builddir/build/BUILD/shoulda-context-1.1.5/usr/share/gems/gems/shoulda-context-1.1.5/lib/shoulda/context/context.rb:400:in `call'
    /builddir/build/BUILD/shoulda-context-1.1.5/usr/share/gems/gems/shoulda-context-1.1.5/lib/shoulda/context/context.rb:400:in `block in create_test_from_should_hash'
 16) Error:
HelpersTest#test: an array of values should contain "abc". :
NameError: uninitialized constant Test::Unit::AssertionFailedError
    /builddir/build/BUILD/shoulda-context-1.1.5/usr/share/gems/gems/shoulda-context-1.1.5/test/shoulda/helpers_test.rb:12:in `block (3 levels) in <class:HelpersTest>'
    /builddir/build/BUILD/shoulda-context-1.1.5/usr/share/gems/gems/shoulda-context-1.1.5/lib/shoulda/context/context.rb:400:in `call'
    /builddir/build/BUILD/shoulda-context-1.1.5/usr/share/gems/gems/shoulda-context-1.1.5/lib/shoulda/context/context.rb:400:in `block in create_test_from_should_hash'
 17) Error:
HelpersTest#test: an array of values should contain /b/. :
NameError: uninitialized constant Test::Unit::AssertionFailedError
    /builddir/build/BUILD/shoulda-context-1.1.5/usr/share/gems/gems/shoulda-context-1.1.5/test/shoulda/helpers_test.rb:12:in `block (3 levels) in <class:HelpersTest>'
    /builddir/build/BUILD/shoulda-context-1.1.5/usr/share/gems/gems/shoulda-context-1.1.5/lib/shoulda/context/context.rb:400:in `call'
    /builddir/build/BUILD/shoulda-context-1.1.5/usr/share/gems/gems/shoulda-context-1.1.5/lib/shoulda/context/context.rb:400:in `block in create_test_from_should_hash'
 18) Error:
HelpersTest#test: an array of values should contain 3. :
NameError: uninitialized constant Test::Unit::AssertionFailedError
    /builddir/build/BUILD/shoulda-context-1.1.5/usr/share/gems/gems/shoulda-context-1.1.5/test/shoulda/helpers_test.rb:12:in `block (3 levels) in <class:HelpersTest>'
    /builddir/build/BUILD/shoulda-context-1.1.5/usr/share/gems/gems/shoulda-context-1.1.5/lib/shoulda/context/context.rb:400:in `call'
    /builddir/build/BUILD/shoulda-context-1.1.5/usr/share/gems/gems/shoulda-context-1.1.5/lib/shoulda/context/context.rb:400:in `block in create_test_from_should_hash'
 19) Error:
HelpersTest#test: an array of values should not contain 'wtf'. :
NameError: uninitialized constant Test::Unit::AssertionFailedError
    /builddir/build/BUILD/shoulda-context-1.1.5/usr/share/gems/gems/shoulda-context-1.1.5/test/shoulda/helpers_test.rb:20:in `block (2 levels) in <class:HelpersTest>'
    /builddir/build/BUILD/shoulda-context-1.1.5/usr/share/gems/gems/shoulda-context-1.1.5/lib/shoulda/context/context.rb:400:in `call'
    /builddir/build/BUILD/shoulda-context-1.1.5/usr/share/gems/gems/shoulda-context-1.1.5/lib/shoulda/context/context.rb:400:in `block in create_test_from_should_hash'
 20) Error:
ShouldMatcherTest#test: a should block with a matcher should fail with a failing matcher. :
NameError: uninitialized constant Test::Unit::TestResult
    /builddir/build/BUILD/shoulda-context-1.1.5/usr/share/gems/gems/shoulda-context-1.1.5/test/shoulda/context_test.rb:211:in `setup'
 21) Error:
HelpersTest#test: a matching matcher when given to assert_rejects and matcher does not have :does_not_match? should fail. :
NameError: uninitialized constant Test::Unit::AssertionFailedError
    /builddir/build/BUILD/shoulda-context-1.1.5/usr/share/gems/gems/shoulda-context-1.1.5/test/shoulda/helpers_test.rb:85:in `rescue in block (4 levels) in <class:HelpersTest>'
    /builddir/build/BUILD/shoulda-context-1.1.5/usr/share/gems/gems/shoulda-context-1.1.5/test/shoulda/helpers_test.rb:83:in `block (4 levels) in <class:HelpersTest>'
    /builddir/build/BUILD/shoulda-context-1.1.5/usr/share/gems/gems/shoulda-context-1.1.5/lib/shoulda/context/context.rb:418:in `call'
    /builddir/build/BUILD/shoulda-context-1.1.5/usr/share/gems/gems/shoulda-context-1.1.5/lib/shoulda/context/context.rb:418:in `block in run_current_setup_blocks'
    /builddir/build/BUILD/shoulda-context-1.1.5/usr/share/gems/gems/shoulda-context-1.1.5/lib/shoulda/context/context.rb:417:in `each'
    /builddir/build/BUILD/shoulda-context-1.1.5/usr/share/gems/gems/shoulda-context-1.1.5/lib/shoulda/context/context.rb:417:in `run_current_setup_blocks'
    /builddir/build/BUILD/shoulda-context-1.1.5/usr/share/gems/gems/shoulda-context-1.1.5/lib/shoulda/context/context.rb:399:in `block in create_test_from_should_hash'
 22) Error:
ShouldMatcherTest#test: a should block with a matcher should pass with a passing matcher. :
NameError: uninitialized constant Test::Unit::TestResult
    /builddir/build/BUILD/shoulda-context-1.1.5/usr/share/gems/gems/shoulda-context-1.1.5/test/shoulda/context_test.rb:211:in `setup'
 23) Error:
ShouldMatcherTest#test: a should block with a matcher should provide the subject. :
NameError: uninitialized constant Test::Unit::TestResult
    /builddir/build/BUILD/shoulda-context-1.1.5/usr/share/gems/gems/shoulda-context-1.1.5/test/shoulda/context_test.rb:211:in `setup'
 24) Error:
ShouldMatcherTest#test: a should block with a matcher within a context should fail with a failing matcher. :
NameError: uninitialized constant Test::Unit::TestResult
    /builddir/build/BUILD/shoulda-context-1.1.5/usr/share/gems/gems/shoulda-context-1.1.5/test/shoulda/context_test.rb:211:in `setup'
 25) Error:
ShouldMatcherTest#test: a should block with a matcher within a context should generate a test using the matcher's description. :
NameError: uninitialized constant Test::Unit::TestResult
    /builddir/build/BUILD/shoulda-context-1.1.5/usr/share/gems/gems/shoulda-context-1.1.5/test/shoulda/context_test.rb:211:in `setup'
 26) Error:
ShouldMatcherTest#test: a should block with a matcher within a context should pass with a passing matcher. :
NameError: uninitialized constant Test::Unit::TestResult
    /builddir/build/BUILD/shoulda-context-1.1.5/usr/share/gems/gems/shoulda-context-1.1.5/test/shoulda/context_test.rb:211:in `setup'
 27) Error:
ShouldMatcherTest#test: a should block with a matcher within a context should provide the subject. :
NameError: uninitialized constant Test::Unit::TestResult
    /builddir/build/BUILD/shoulda-context-1.1.5/usr/share/gems/gems/shoulda-context-1.1.5/test/shoulda/context_test.rb:211:in `setup'
 28) Error:
ShouldMatcherTest#test: a should_not block with a matcher should fail with a passing matcher. :
NameError: uninitialized constant Test::Unit::TestResult
    /builddir/build/BUILD/shoulda-context-1.1.5/usr/share/gems/gems/shoulda-context-1.1.5/test/shoulda/context_test.rb:211:in `setup'
 29) Error:
ShouldMatcherTest#test: a should_not block with a matcher should generate a test using the matcher's description. :
NameError: uninitialized constant Test::Unit::TestResult
    /builddir/build/BUILD/shoulda-context-1.1.5/usr/share/gems/gems/shoulda-context-1.1.5/test/shoulda/context_test.rb:211:in `setup'
 30) Error:
ShouldMatcherTest#test: a should_not block with a matcher should pass with a failing matcher. :
NameError: uninitialized constant Test::Unit::TestResult
    /builddir/build/BUILD/shoulda-context-1.1.5/usr/share/gems/gems/shoulda-context-1.1.5/test/shoulda/context_test.rb:211:in `setup'
 31) Error:
ShouldMatcherTest#test: a should_not block with a matcher should provide the subject. :
NameError: uninitialized constant Test::Unit::TestResult
    /builddir/build/BUILD/shoulda-context-1.1.5/usr/share/gems/gems/shoulda-context-1.1.5/test/shoulda/context_test.rb:211:in `setup'
 32) Error:
ShouldMatcherTest#test: a should_not block with a matcher within a context should fail with a passing matcher. :
NameError: uninitialized constant Test::Unit::TestResult
    /builddir/build/BUILD/shoulda-context-1.1.5/usr/share/gems/gems/shoulda-context-1.1.5/test/shoulda/context_test.rb:211:in `setup'
 33) Error:
ShouldMatcherTest#test: a should_not block with a matcher within a context should generate a test using the matcher's description. :
NameError: uninitialized constant Test::Unit::TestResult
    /builddir/build/BUILD/shoulda-context-1.1.5/usr/share/gems/gems/shoulda-context-1.1.5/test/shoulda/context_test.rb:211:in `setup'
 34) Error:
ShouldMatcherTest#test: a should_not block with a matcher within a context should pass with a failing matcher. :
NameError: uninitialized constant Test::Unit::TestResult
    /builddir/build/BUILD/shoulda-context-1.1.5/usr/share/gems/gems/shoulda-context-1.1.5/test/shoulda/context_test.rb:211:in `setup'
 35) Error:
ShouldMatcherTest#test: a should_not block with a matcher within a context should provide the subject. :
NameError: uninitialized constant Test::Unit::TestResult
    /builddir/build/BUILD/shoulda-context-1.1.5/usr/share/gems/gems/shoulda-context-1.1.5/test/shoulda/context_test.rb:211:in `setup'
 36) Error:
HelpersTest#test: a matching matcher should fail when given to assert_accepts with non-matching message. :
NameError: uninitialized constant Test::Unit::AssertionFailedError
    /builddir/build/BUILD/shoulda-context-1.1.5/usr/share/gems/gems/shoulda-context-1.1.5/test/shoulda/helpers_test.rb:58:in `block (2 levels) in <class:HelpersTest>'
    /builddir/build/BUILD/shoulda-context-1.1.5/usr/share/gems/gems/shoulda-context-1.1.5/lib/shoulda/context/context.rb:400:in `call'
    /builddir/build/BUILD/shoulda-context-1.1.5/usr/share/gems/gems/shoulda-context-1.1.5/lib/shoulda/context/context.rb:400:in `block in create_test_from_should_hash'
 37) Error:
HelpersTest#test: a matcher using antiquated syntax when given to assert_accepts should use the error message from the matcher. :
NameError: uninitialized constant Test::Unit::AssertionFailedError
    /builddir/build/BUILD/shoulda-context-1.1.5/usr/share/gems/gems/shoulda-context-1.1.5/test/shoulda/helpers_test.rb:165:in `rescue in block (3 levels) in <class:HelpersTest>'
    /builddir/build/BUILD/shoulda-context-1.1.5/usr/share/gems/gems/shoulda-context-1.1.5/test/shoulda/helpers_test.rb:163:in `block (3 levels) in <class:HelpersTest>'
    /builddir/build/BUILD/shoulda-context-1.1.5/usr/share/gems/gems/shoulda-context-1.1.5/lib/shoulda/context/context.rb:418:in `call'
    /builddir/build/BUILD/shoulda-context-1.1.5/usr/share/gems/gems/shoulda-context-1.1.5/lib/shoulda/context/context.rb:418:in `block in run_current_setup_blocks'
    /builddir/build/BUILD/shoulda-context-1.1.5/usr/share/gems/gems/shoulda-context-1.1.5/lib/shoulda/context/context.rb:417:in `each'
    /builddir/build/BUILD/shoulda-context-1.1.5/usr/share/gems/gems/shoulda-context-1.1.5/lib/shoulda/context/context.rb:417:in `run_current_setup_blocks'
    /builddir/build/BUILD/shoulda-context-1.1.5/usr/share/gems/gems/shoulda-context-1.1.5/lib/shoulda/context/context.rb:399:in `block in create_test_from_should_hash'
 38) Error:
HelpersTest#test: a matcher using antiquated syntax when given to assert_accepts should fail. :
NameError: uninitialized constant Test::Unit::AssertionFailedError
    /builddir/build/BUILD/shoulda-context-1.1.5/usr/share/gems/gems/shoulda-context-1.1.5/test/shoulda/helpers_test.rb:165:in `rescue in block (3 levels) in <class:HelpersTest>'
    /builddir/build/BUILD/shoulda-context-1.1.5/usr/share/gems/gems/shoulda-context-1.1.5/test/shoulda/helpers_test.rb:163:in `block (3 levels) in <class:HelpersTest>'
    /builddir/build/BUILD/shoulda-context-1.1.5/usr/share/gems/gems/shoulda-context-1.1.5/lib/shoulda/context/context.rb:418:in `call'
    /builddir/build/BUILD/shoulda-context-1.1.5/usr/share/gems/gems/shoulda-context-1.1.5/lib/shoulda/context/context.rb:418:in `block in run_current_setup_blocks'
    /builddir/build/BUILD/shoulda-context-1.1.5/usr/share/gems/gems/shoulda-context-1.1.5/lib/shoulda/context/context.rb:417:in `each'
    /builddir/build/BUILD/shoulda-context-1.1.5/usr/share/gems/gems/shoulda-context-1.1.5/lib/shoulda/context/context.rb:417:in `run_current_setup_blocks'
    /builddir/build/BUILD/shoulda-context-1.1.5/usr/share/gems/gems/shoulda-context-1.1.5/lib/shoulda/context/context.rb:399:in `block in create_test_from_should_hash'
 39) Error:
HelpersTest#test: a matcher using antiquated syntax should fail when given to assert_rejects with a non-matching message. :
NameError: uninitialized constant Test::Unit::AssertionFailedError
    /builddir/build/BUILD/shoulda-context-1.1.5/usr/share/gems/gems/shoulda-context-1.1.5/test/shoulda/helpers_test.rb:156:in `block (2 levels) in <class:HelpersTest>'
    /builddir/build/BUILD/shoulda-context-1.1.5/usr/share/gems/gems/shoulda-context-1.1.5/lib/shoulda/context/context.rb:400:in `call'
    /builddir/build/BUILD/shoulda-context-1.1.5/usr/share/gems/gems/shoulda-context-1.1.5/lib/shoulda/context/context.rb:400:in `block in create_test_from_should_hash'
 40) Error:
ShouldMatcherTest#test: a should block with a matcher should generate a test using the matcher's description. :
NameError: uninitialized constant Test::Unit::TestResult
    /builddir/build/BUILD/shoulda-context-1.1.5/usr/share/gems/gems/shoulda-context-1.1.5/test/shoulda/context_test.rb:211:in `setup'
107 tests, 128 assertions, 10 failures, 30 errors, 0 skips
ruby -v: ruby 2.0.0p247 (2013-06-27 revision 41674) [i386-linux]
```

Can you make shoulda-context work with minitest?

**Comment by mcmire** [comment]
I doubt you are working on this anymore, but just in case, I finally released shoulda-context 2.0.0 which should fix this issue.
