### ISSUE TITLE
Original test backtrace should be preserved

### ISSUE THREAD

**Issue by y8** [thoughtbot/shoulda-context#9]
Hey.

Right now shoulda-context breaking backtrace:

```
SKIP test: Something happend.  (0:00:00.465)
     Test me!

     gems/shoulda-context-2f8fad6003da/lib/shoulda/context/context.rb:398:in `call'
     gems/shoulda-context-2f8fad6003da/lib/shoulda/context/context.rb:398:in `block in create_test_from_should_hash'
     gems/activesupport-3.2.0/lib/active_support/testing/setup_and_teardown.rb:35:in `block in run'
     gems/activesupport-3.2.0/lib/active_support/callbacks.rb:425:in `_run__2556407847287019068__setup__2472431954389510972__callbacks'
     gems/activesupport-3.2.0/lib/active_support/callbacks.rb:405:in `__run_callback'
     gems/activesupport-3.2.0/lib/active_support/callbacks.rb:385:in `_run_setup_callbacks'
     gems/activesupport-3.2.0/lib/active_support/callbacks.rb:81:in `run_callbacks'
     gems/activesupport-3.2.0/lib/active_support/testing/setup_and_teardown.rb:34:in `run'
```

This is not good. Shoulda should preserve original path to block in backtrace (should { } in *_test.rb)

**Comment by cseelus** [comment]
@y8 and anyone else who has this problem:

This is probably a [minitest-reporters](https://github.com/kern/minitest-reporters) problem with all but the default reporter, which is even mentioned [directly in the README](https://github.com/kern/minitest-reporters#caveats).

**Comment by y8** [comment]
@cseelus huh, since "jarrett authored on Aug 29, 2014". :) But thanks anyway!
